version: "2"
volumes:
    mongo-data:
services:
  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: "admin"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
  api:
    restart: always
    image: scpomedialab/ouatterrir-api
    build: .
    links:
     - "mongo"
    environment:
      MONGO_DB: "ouatterrir"
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: "${MONGO_USER}"
      MONGO_PASSWORD: "${MONGO_PASSWORD}"
      API_PORT: 4000
  client:
    restart: always
    image: scpomedialab/ouatterrir-client
    build: ./client
    links:
     - "api"
    environment:
      API_HOST: api
      API_PORT: 4000
    ports:
      - "${PUBLIC_PORT}:80"
