apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc-backup.yml
  - db/pvc.yml
  - db/deployment.yml
  - db/service.yml
  - db/cronjob.yml
  - api/deployment.yml
  - api/service.yml
  - client/deployment.yml
  - client/service.yml

commonLabels:
  owner: medialab
  app: ouatterrir
